### ISSUE TITLE
RSS Feed is broken

### ISSUE THREAD

**Issue by siddadel** [PARINetwork/pari#296] opened 2018-01-23 13:21 UTC
RSS feed available here:
https://ruralindiaonline.org/feeds/list

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fruralindiaonline.org%2Ffeeds%2Fall%3Fformat%3Drss

We need RSS feed to be functional, valid and well-formed to use webapps like Zapier and apply to be included by aggregators.

**Comment by siddadel** [comment] 2018-01-23 13:39
http://www.feedvalidator.org/check.cgi?url=https%3a%2f%2fruralindiaonline.org%2ffeeds%2fall

**Comment by gounder** [comment] 2019-05-31 13:44
Duplicate of #384

**Closed by gounder** 2019-05-31 13:44 UTC
Labels: High Priority, Show Stopper, Small Work, good first issue, help wanted
